hookBlockchain.go
added vmType for which the new address should be generated
=> added vmType for which the new address should be generated

output.go
* Convert `VMOutput.OutputAccounts` into a map
* Convert `OutputAccount.StorageUpdates` into a map
=> Vmoutput maps

atArgumentParser_test.go, go.sum
=> empty argument tests

hookBlockchain.go
```
+ GetUserAccount
+ GetShardOfAddress
+ IsSmartContract
- AccountExists
- GetBalance
- GetNonce
- IsCodeEmpty
- GetCode 
```
=> Add some hooks & remove others

output.go
vmcommon prepared for multiple asyncCalls and for smart contract library royalties
=> Multi Out Transfers

input.go
vmcommon prepared for esdt transfer to smart contracts
=> esdt-token-transfer

hookBlockchain.go
=> Clear compiled codes

executionHandler.go
=> New-func-gas-schedule-change

.github/workflows/pr-tests.yml, Makefile, builtInFunctions/esdtNFTAddQuantity.go, builtInFunctions/esdtNFTBurn.go, builtInFunctions/esdtNFTCreate.go, builtInFunctions/esdtNFTTransfer.go, builtInFunctions/logsAndEvents_test.go
- Added extra logs for NFT operations
- Added a Github action that will run tests on every push
=> Extra logs and action

builtInFunctions/esdtBurn.go, builtInFunctions/esdtFreezeWipe.go, builtInFunctions/esdtLocalBurn.go, builtInFunctions/esdtLocalBurn_test.go, builtInFunctions/esdtLocalMint.go, builtInFunctions/esdtLocalMint_test.go, builtInFunctions/esdtTransfer.go, builtInFunctions/logsAndEvents.go
Added logs and events for the ESDT operations with `fungible tokens`
=> Logs and events ESDT fungible

input.go, interface.go, parsers/errors.go, parsers/esdtTransferParser.go, parsers/esdtTransferParser_test.go
=> parse esdt transfers

builtInFunctions/esdtBurn.go, builtInFunctions/esdtFreezeWipe.go, builtInFunctions/esdtLocalBurn.go, builtInFunctions/esdtLocalBurn_test.go, builtInFunctions/esdtLocalMint.go, builtInFunctions/esdtLocalMint_test.go, builtInFunctions/esdtNFTAddQuantity.go, builtInFunctions/esdtNFTAddUri.go, builtInFunctions/esdtNFTBurn.go, builtInFunctions/esdtNFTCreate.go, builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtTransfer.go, builtInFunctions/logsAndEvents.go, builtInFunctions/logsAndEvents_test.go, builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/updateNFTAttributes.go
Same logs for all ESDT operations
=> Same logs for ESDT

builtInFunctions/keyValueStorage.go
- added test point in keyValueStorage.go
=> Test point in keyValueStorage.go

builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtTransfer.go, builtInFunctions/multiESDTNFTTransfer.go
fixed "transfer to meta" enabled logs
=> log fixes for transfer to meta flag

builtInFunctions/keyValueStorage.go, builtInFunctions/keyValueStorage_test.go
- fixed the destination account check in the SaveKeyValue builtin function
=> Fixed the SaveKeyValue destination account check

builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/multiESDTNFTTransfer_test.go
fixed payable check on multitransfer
=> fixed payable check on multi transfer

builtInFunctions/errors.go, builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/multiESDTNFTTransfer_test.go
=> Change error insufficient quantity multi transfer

builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtTransfer.go, builtInFunctions/multiESDTNFTTransfer.go
=> new logic for isSCCallAfter

builtInFunctions/esdtRoles.go, builtInFunctions/esdtRoles_test.go, builtInFunctions/factory.go, go.mod, go.sum
NFT creation on multiple shards
=> NFT nonce per lastByte

builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/multiESDTNFTTransfer_test.go
Fix check on cross shard multi
=> Fix check on cross shard multi

parsers/esdtTransferParser.go, parsers/esdtTransferParser_test.go
make esdt transfer parser smart
=> make esdt transfer parser smart

interface.go, mock/accountsStub.go
remove GetNumCheckpoints from AccountsAdapter
=> AccountsAdapter update

builtInFunctions/esdtNFTTransfer.go
Fixed the event that is generated on destination for an ESDT NFT Transfer
=> Fix log esdt nft transfer

builtInFunctions/creator.go, builtInFunctions/esdtNFTCreate.go, builtInFunctions/esdtNFTCreate_test.go, builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/multiESDTNFTTransfer_test.go, go.mod, go.sum
added new mode to create NFTs on destination by caller
=> added new mode to create NFTs on destination by caller

builtInFunctions/creator.go, builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtNFTTransfer_test.go
check nft transfer quantity not zero
=> check nft transfer quantity not zero

builtInFunctions/esdtDataStorage.go, builtInFunctions/esdtDataStorage_test.go, builtInFunctions/esdtNFTTransfer.go
=> save nft metadata always

builtInFunctions/esdtDataStorage.go, builtInFunctions/esdtDataStorage_test.go, builtInFunctions/esdtNFTTransfer_test.go
Fix nft freeze check on colleciton
=> Fix nft freeze check on colleciton

builtInFunctions/esdtFreezeWipe.go, builtInFunctions/esdtNFTAddUri.go, builtInFunctions/esdtNFTCreateRoleTransfer.go, builtInFunctions/esdtRoles.go, builtInFunctions/logsAndEvents.go, builtInFunctions/updateNFTAttributes.go
- Added logs and events on ESDT built-in functions
=> Logs and events built in functions

builtInFunctions/creator.go, interface.go
=> extend interfaces

builtInFunctions/creator.go, builtInFunctions/creator_test.go, builtInFunctions/esdtGlobalSettings.go, builtInFunctions/esdtGlobalSettings_test.go, builtInFunctions/esdtLocalBurn.go, builtInFunctions/esdtLocalBurn_test.go, builtInFunctions/esdtMetaData.go, builtInFunctions/esdtNFTBurn.go, builtInFunctions/esdtNFTBurn_test.go, common.go, interface.go, mock/pauseHandlerStub.go
=> Burn role for all

builtInFunctions/freezeAccount.go, builtInFunctions/freezeAccount_test.go, interface.go, mock/guardedAccountHandlerStub.go
Clean pending or disabled guardian on freeze.
=> freezeAccount if successful cleans up pending or disabled guardians

builtInFunctions/esdtTransfer.go, builtInFunctions/esdtTransfer_test.go
=> Backwards compatibility fix

builtInFunctions/creator.go, builtInFunctions/creator_test.go, builtInFunctions/disabledPayable.go, builtInFunctions/errors.go, builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtNFTTransfer_test.go, builtInFunctions/esdtTransfer.go, builtInFunctions/esdtTransfer_test.go, builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/multiESDTNFTTransfer_test.go, builtInFunctions/payable.go, builtInFunctions/payable_test.go, interface.go, mock/payableHandlerStub.go, parsers/callArgsParser.go, parsers/callArgsParser_test.go
refactor and added test and flags
Added fix for asynchronous callback check
Added fix for returnAfterError checks
=> refactor payable checks

builtInFunctions/esdtDataStorage.go, builtInFunctions/esdtNFTBurn.go, builtInFunctions/esdtNFTBurn_test.go, builtInFunctions/esdtNFTCreate.go
in case of a ESDTNFTBurn operation, decrease the liquidity from system account
=> Remove liquidity for nft burn

builtInFunctions/esdtDataStorage.go, builtInFunctions/esdtNFTBurn.go, builtInFunctions/esdtNFTBurn_test.go, builtInFunctions/esdtNFTCreate.go
=> Merge main feet freeze account

builtInFunctions/esdtFreezeWipe.go, builtInFunctions/esdtFreezeWipe_test.go, common.go, common_test.go
- In the event / log `ESDTFreeze`, add the frozen amount as `topics[2]` (previously fixed to `0`).
- In the event / log `ESDTWipe`, add the wiped amount as `topics[2]` (previously fixed to `0`).
=> In the events "ESDTFreeze", "ESDTWipe", specify the "frozen" / "wiped" amount.

builtInFunctions/creator.go, builtInFunctions/esdtDataStorage.go, builtInFunctions/esdtDataStorage_test.go, builtInFunctions/esdtNFTBurn_test.go, builtInFunctions/esdtNFTTransfer_test.go
=> No liquidity for old tokens

go.mod, go.sum, parsers/dataField/args.go, parsers/dataField/parseMultiESDTNFTTransfer.go, parsers/dataField/parseMultiESDTNFTTransfer_test.go, parsers/dataField/parseSingleESDTTransfer_test.go, parsers/dataField/parseSingleNFTTransfer.go, parsers/dataField/parseSingleNFTTransfer_test.go, parsers/dataField/parser.go, parsers/dataField/parser_test.go
- Removed the `ShardCoordinator` from the `datafield` parser
=> Remove shard coordinator from the `datafield parser`

interface.go, mock/enableEpochsHandlerStub.go
- update the EnableEpochsHandler interface
=> Update the EnableEpochsHandler interface

builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtNFTTransfer_test.go, builtInFunctions/esdtTransfer.go, builtInFunctions/esdtTransfer_test.go, builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/multiESDTNFTTransfer_test.go, interface.go, mock/enableEpochsHandlerStub.go
Removed `IsTransferToMeta` obsolete flag
=> FIX: Delete IsTransferToMeta obsolete flag

interface.go, mock/enableEpochsHandlerStub.go
=> Merge rc/v1.6.0 in pubkeyconv 8mar

builtInFunctions/deleteUserName.go, builtInFunctions/deleteUserName_test.go, builtInFunctions/saveUserName.go, builtInFunctions/saveUserName_test.go
=> Fix gasCost on userName funcs

go.mod, go.sum, interface.go, mock/enableEpochsHandlerStub.go, parsers/dataField/parseSingleNFTTransfer_test.go, parsers/dataField/utils.go, parsers/dataField/utils_test.go
Merge rc into staking v4 21 mar 2023
=> Merge rc into stakingv4 21 mar 2023

go.mod, go.sum
- proper release for mx-chain-core-go
=> Proper release for mx-chain-core-go

builtInFunctions/guardAccount.go, builtInFunctions/guardAccount_test.go, builtInFunctions/setGuardian.go, builtInFunctions/setGuardian_test.go, builtInFunctions/unGuardAccount.go, builtInFunctions/unGuardAccount_test.go
- Added events for built-in functions: `SetGuardian`, `GuardAccount` and `UnGuardAccount`
=> Logs freeze account

go.mod, go.sum
=> Latest mx-chain-core-go

builtInFunctions/setGuardian.go, builtInFunctions/setGuardian_test.go
verify arguments before usage.
=> args check before referencing args

parsers/dataField/parser_test.go, parsers/dataField/utils.go
- Extended the built-in function list with the guardians' operations
=> extend built-in function list

go.mod, go.sum
=> Update core for sovereign

address.go, address_test.go, builtInFunctions/claimDeveloperRewards.go, builtInFunctions/claimDeveloperRewards_test.go, builtInFunctions/esdtBurn.go, builtInFunctions/esdtNFTCreateRoleTransfer.go, builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtTransfer.go, builtInFunctions/migrateDataTrie.go, builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/saveUserName.go, errors.go, go.mod, go.sum, input.go, interface.go, output.go
Merge rc 1 6 sovereign 3 jul 2023
=> Merge rc 1 6 sovereign 3 jul 2023

.github/workflows/golangci-lint.yml, .github/workflows/pr-tests.yml, go.mod, go.sum
- new go definition in go.mod 
- reworked GitHub workflow files
=> New go definition in go.mod (v1.20)

builtInFunctions/changeOwnerAddress.go, builtInFunctions/changeOwnerAddress_test.go, interface.go, mock/enableEpochsHandlerStub.go
=> Merge rc in logs

builtInFunctions/changeOwnerAddress.go, builtInFunctions/changeOwnerAddress_test.go, builtInFunctions/creator.go, interface.go, mock/enableEpochsHandlerStub.go
- Extended the built-in function `ChangeOwnerAddress` in order to support an event when the function is called through a smart contract call cross-shard
- Added also an activation flag for this feature
=> Bug-fix change owner address built-in function

builtInFunctions/migrateDataTrie.go, builtInFunctions/migrateDataTrie_test.go, interface.go, mock/enableEpochsHandlerStub.go
=> New activation flag

builtInFunctions/flags.go, builtInFunctions/migrateDataTrie.go, builtInFunctions/migrateDataTrie_test.go, go.mod, go.sum
Merge rc 1 7 into staking v4 30 jan 2024
=> Merge rc 1 7 into staking v4 30 jan 2024

parsers/dataField/parseMultiESDTNFTTransfer_test.go, parsers/dataField/parseSingleESDTTransfer_test.go, parsers/dataField/parseSingleNFTTransfer_test.go, parsers/dataField/parser.go, parsers/dataField/parser_test.go
- Exported the const for the `transfer` operation
=> Transfer operation exported const

builtInFunctions/esdtGlobalSettings.go, builtInFunctions/esdtGlobalSettings_test.go, go.sum
No need to load account when it is already loaded - only in Sovereign
=> Fix sovereign set role for all

builtInFunctions/esdtTransferRole.go
Better code for SetTransferRole. Fixing load account if not needed.
=> Better code for SetTransferRole

builtInFunctions/esdtRoles.go
FIX: Linter in feat esdt prefix
=> FIX: Linter

builtInFunctions/creator.go, builtInFunctions/esdtMetaDataRecreate.go, builtInFunctions/esdtMetaDataRecreate_test.go, builtInFunctions/esdtMetaDataUpdate.go, builtInFunctions/esdtMetaDataUpdate_test.go, builtInFunctions/esdtModifyCreator.go, builtInFunctions/esdtModifyRoyalties.go, builtInFunctions/esdtSetNewURIs.go, parsers/dataField/utils.go
- Fixes
- Added log events for the new builtin functions
=> ESDT improvements fixes

builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/multiESDTNFTTransfer_test.go, common.go, parsers/dataField/parseMultiESDTNFTTransfer_test.go
- Added a new constant for the EGLD identifier in case of a MultiESDTNFTTransfer with egld transfer
=> EGLD identifier const

builtInFunctions/baseComponentsHolder.go, builtInFunctions/baseComponentsHolder_test.go, builtInFunctions/creator.go, builtInFunctions/creator_test.go, builtInFunctions/esdtDataStorage.go, builtInFunctions/esdtDataStorage_test.go, builtInFunctions/esdtMetaDataRecreate.go, builtInFunctions/esdtMetaDataRecreate_test.go, builtInFunctions/esdtMetaDataUpdate.go, builtInFunctions/esdtMetaDataUpdate_test.go, builtInFunctions/esdtModifyCreator.go, builtInFunctions/esdtModifyCreator_test.go, builtInFunctions/esdtModifyRoyalties.go, builtInFunctions/esdtModifyRoyalties_test.go, builtInFunctions/esdtNFTAddQuantity.go, builtInFunctions/esdtNFTAddUri.go, builtInFunctions/esdtNFTAddUri_test.go, builtInFunctions/esdtNFTBurn.go, builtInFunctions/esdtNFTCreate.go, builtInFunctions/esdtNFTTransfer.go, builtInFunctions/esdtNFTTransfer_test.go, builtInFunctions/esdtSetNewURIs.go, builtInFunctions/esdtSetNewURIs_test.go, builtInFunctions/multiESDTNFTTransfer.go, builtInFunctions/updateNFTAttributes.go, builtInFunctions/updateNFTAttributes_test.go, go.mod, go.sum, interface.go, mock/esdtStorageHandlerStub.go
=> Update barnard wirh rc v1.7.next1

parsers/dataField/parser.go, parsers/dataField/parser_test.go
- Extract token identifier for the new esdt build in functions
=> Token identifier for the new esdt build in functions
